# Generated by Django 2.2.4 on 2020-06-03 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_animal', '0002_auto_20200531_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='how_was_it_welcomed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='how_was_it_welcomed', to='app_animal.Status'),
        ),
    ]
