# Generated by Django 2.2.4 on 2020-06-03 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_animal', '0003_auto_20200603_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='color2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color2', to='app_animal.Color'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='color3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color3', to='app_animal.Color'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
