# Generated by Django 2.2.4 on 2020-06-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_animal', '0004_auto_20200603_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='lost_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
